# .github/workflows/teams-notify.yml
name: Notify Microsoft Teams on PR Publish

on:
  pull_request:
    branches:
    - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Teams
        uses: skitionek/notify-microsoft-teams@v1.0.9
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: "[#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}"
          # summary: |
          #   **Branch**: `${{ github.event.pull_request.head.ref }}`
          #   **PR Creator**: ${{ github.event.pull_request.user.login }}
          #   **PR Description**:
          #   ${{ github.event.pull_request.body }}
          #
          #   [PR Overview](${{ github.event.pull_request.html_url }})
